name: tesla_android
description: Tesla Android

publish_to: 'none'

version: 2022.45.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pointer_interceptor: ^0.9.0+1
  http: ^0.13.4
  web_socket_channel: ^2.2.0
  get_it: ^7.0.0
  injectable: ^1.5.3
  flavor: ^2.0.0
  flutter_bloc: ^8.0.1
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  flutter_markdown: ^0.6.10
  qr_flutter: ^4.0.0
  retrofit: '>=3.0.0 <4.0.0'
  logger: any
  dio: 4.0.4
  json_serializable: ^6.2.0
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.2
  injectable_generator: ^1.5.3
  retrofit_generator: '>=4.0.0 <5.0.0'

flutter:
  assets:
    - images/png/
  uses-material-design: true