name: Build released version

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          targetBranch: release
